### ISSUE TITLE
train vespcn model error in VSRTorch

### ISSUE THREAD

**Issue by HymEric** [LoSealL/VideoSuperResolution#27]
Traceback (most recent call last):
  File "train.py", line 124, in <module>
    main()
  File "train.py", line 118, in main
    t.fit([tloader, vloader], train_config)
  File "/home/disk1/hym/pycharm_remote/VideoSuperResolution-master/VSRTorch/Framework/Trainer.py", line 127, in fit
    self.fn_train_each_step(label, feature, name, post)
  File "/home/disk1/hym/pycharm_remote/VideoSuperResolution-master/VSRTorch/Framework/Trainer.py", line 148, in fn_train_each_step
    loss = self.model.train([feature], [label], v.lr)
  File "/home/disk1/hym/pycharm_remote/VideoSuperResolution-master/VSRTorch/Models/Vespcn.py", line 25, in train
    sr, warps, flows = self.vespcn(*frames)
  File "/home/disk1/hym/anaconda3/envs/pytorch100/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/disk1/hym/pycharm_remote/VideoSuperResolution-master/VSRTorch/Models/vespcn/ops.py", line 100, in forward
    warp, flow = self.mc(target, r)
  File "/home/disk1/hym/anaconda3/envs/pytorch100/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/disk1/hym/pycharm_remote/VideoSuperResolution-master/VSRTorch/Models/vespcn/ops.py", line 58, in forward
    flow0 = self.coarse_flow(torch.cat([ref, target], 1))
  File "/home/disk1/hym/anaconda3/envs/pytorch100/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/disk1/hym/anaconda3/envs/pytorch100/lib/python3.7/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/disk1/hym/anaconda3/envs/pytorch100/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/disk1/hym/anaconda3/envs/pytorch100/lib/python3.7/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/disk1/hym/anaconda3/envs/pytorch100/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/disk1/hym/anaconda3/envs/pytorch100/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 320, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: Expected 4-dimensional input for 4-dimensional weight [24, 6, 5, 5], but got 3-dimensional input of size [16, 64, 32] instead

**Comment by LoSealL** [comment]
Change to video related dataset.

**Comment by HymEric** [comment]
Thank you. I have solved it.

**Comment by RuyiLuo** [comment]
When I run `python train.py --model=srcnn --cuda --dataset=mydata` in pytorch environment.
Traceback:
```
Traceback (most recent call last):
  File "train.py", line 17, in <module>
    from VSRTorch.Models import get_model, list_supported_models
ModuleNotFoundError: No module named 'VSRTorch'
```
I didn't change VSRTorch's path, So I don't know what happen with this.
Thanks.

**Comment by RuyiLuo** [comment]
Sorry, I soved it.
