### ISSUE TITLE
how to deal with pair-data in vespcn with lr-frames and hr-frames?

### ISSUE THREAD

**Issue by HymEric** [LoSealL/VideoSuperResolution#29]
my data folder tree is:
mydata:
    train_HR:
            001:
                 001.png
                 002.png
                 ........
 train_LRx4:
            001:
                 001.png
                 002.png
                 ........
 valid_HR:
            001:
                 001.png
                 002.png
                 ........
 valid_LRx4:
            001:
                 001.png
                 002.png
                 ........

and run **CUDA_VISIBLE_DEVICES=1 python train.py vespcn --cuda --dataset video_bea --epochs 1000**
**but I have this log, it seems the data is empty.**

'''
(pytorch100) hym@VIPA109:~/pycharm_remote/VideoSuperResolution-master/VSRTorch$ CUDA_VISIBLE_DEVICES=1 python train.py vespcn --cuda --dataset video_bea --epochs 1000
/home/disk1/hym/pycharm_remote/VideoSuperResolution-master/VSR/Util/Config.py:24: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  obj = yaml.load(fd)
2019-04-11 15:56:43,236 INFO: LICENSE: VESPCN is proposed at CVPR2017 by Twitter. Implemented by myself @LoSealL.
2019-04-11 15:56:43,236 INFO: @LoSealL. Video related ops, nets...
/home/disk1/hym/pycharm_remote/VideoSuperResolution-master/VSR/DataLoader/Dataset.py:88: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(fd)
2019-04-11 15:56:46,052 INFO: Total params: 878787
2019-04-11 15:56:46,218 INFO: Restoring params from /home/disk1/hym/pycharm_remote/VideoSuperResolution-master/Results/vespcn/save/vespcn_ep0009.pth
2019-04-11 15:56:46,232 INFO: Fitting: [VESPCN]
Exception in thread fetch_thread_1:
Traceback (most recent call last):
  File "/home/disk1/hym/anaconda3/envs/pytorch100/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/disk1/hym/anaconda3/envs/pytorch100/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/disk1/hym/pycharm_remote/VideoSuperResolution-master/VSR/DataLoader/Loader.py", line 263, in _prefetch
    frames = self.parser[index * interval:(index + 1) * interval]
  File "/home/disk1/hym/pycharm_remote/VideoSuperResolution-master/VSR/DataLoader/Parser/custom_pairs.py", line 42, in __getitem__
    ret += self.gen_frames(copy.deepcopy(vf), vf.frames)
  File "/home/disk1/hym/pycharm_remote/VideoSuperResolution-master/VSR/DataLoader/Parser/custom_pairs.py", line 69, in gen_frames
    lr = [img for img in vf.pair.read_frame(depth)]
  File "/home/disk1/hym/pycharm_remote/VideoSuperResolution-master/VSR/DataLoader/VirtualFile.py", line 352, in read_frame
    image_bytes = [BytesIO(self.read()) for _ in range(frames)]
  File "/home/disk1/hym/pycharm_remote/VideoSuperResolution-master/VSR/DataLoader/VirtualFile.py", line 352, in <listcomp>
    image_bytes = [BytesIO(self.read()) for _ in range(frames)]
  File "/home/disk1/hym/pycharm_remote/VideoSuperResolution-master/VSR/DataLoader/VirtualFile.py", line 144, in read
    raise EOFError('End of File!')
EOFError: End of File!

Exception in thread fetch_thread_0:
Traceback (most recent call last):
  File "/home/disk1/hym/anaconda3/envs/pytorch100/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/disk1/hym/anaconda3/envs/pytorch100/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/disk1/hym/pycharm_remote/VideoSuperResolution-master/VSR/DataLoader/Loader.py", line 263, in _prefetch
    frames = self.parser[index * interval:(index + 1) * interval]
  File "/home/disk1/hym/pycharm_remote/VideoSuperResolution-master/VSR/DataLoader/Parser/custom_pairs.py", line 42, in __getitem__
    ret += self.gen_frames(copy.deepcopy(vf), vf.frames)
  File "/home/disk1/hym/pycharm_remote/VideoSuperResolution-master/VSR/DataLoader/Parser/custom_pairs.py", line 69, in gen_frames
    lr = [img for img in vf.pair.read_frame(depth)]
  File "/home/disk1/hym/pycharm_remote/VideoSuperResolution-master/VSR/DataLoader/VirtualFile.py", line 352, in read_frame
    image_bytes = [BytesIO(self.read()) for _ in range(frames)]
  File "/home/disk1/hym/pycharm_remote/VideoSuperResolution-master/VSR/DataLoader/VirtualFile.py", line 352, in <listcomp>
    image_bytes = [BytesIO(self.read()) for _ in range(frames)]
  File "/home/disk1/hym/pycharm_remote/VideoSuperResolution-master/VSR/DataLoader/VirtualFile.py", line 144, in read
    raise EOFError('End of File!')
EOFError: End of File!

2019-04-11 15:56:46,907 WARNING: frames is empty. [size=3200]
| 2019-04-11 15:56:46 | Epoch: 10/1000 | LR: 0.0001 |
0batch [00:00, ?batch/s]
Exception in thread fetch_thread_0:
Traceback (most recent call last):
  File "/home/disk1/hym/anaconda3/envs/pytorch100/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/disk1/hym/anaconda3/envs/pytorch100/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/disk1/hym/pycharm_remote/VideoSuperResolution-master/VSR/DataLoader/Loader.py", line 263, in _prefetch
    frames = self.parser[index * interval:(index + 1) * interval]
  File "/home/disk1/hym/pycharm_remote/VideoSuperResolution-master/VSR/DataLoader/Parser/custom_pairs.py", line 42, in __getitem__
    ret += self.gen_frames(copy.deepcopy(vf), vf.frames)
  File "/home/disk1/hym/pycharm_remote/VideoSuperResolution-master/VSR/DataLoader/Parser/custom_pairs.py", line 69, in gen_frames
    lr = [img for img in vf.pair.read_frame(depth)]
  File "/home/disk1/hym/pycharm_remote/VideoSuperResolution-master/VSR/DataLoader/VirtualFile.py", line 352, in read_frame
    image_bytes = [BytesIO(self.read()) for _ in range(frames)]
  File "/home/disk1/hym/pycharm_remote/VideoSuperResolution-master/VSR/DataLoader/VirtualFile.py", line 352, in <listcomp>
    image_bytes = [BytesIO(self.read()) for _ in range(frames)]
  File "/home/disk1/hym/pycharm_remote/VideoSuperResolution-master/VSR/DataLoader/VirtualFile.py", line 144, in read
    raise EOFError('End of File!')
EOFError: End of File!

'''

**Comment by LoSealL** [comment]
@HymEric So your training data only has 1 video with N frames?
If so, put your video image files into a sub-folder:
mydata:
|-train_hr
|---video001
|-----image000.png
|-----image001.png
|-----...
|-train_lr
|---video001
|-----image000.png
|-----image001.png
|-----...
...

**Comment by LoSealL** [comment]
Show me your `video_bea` in `datasets.yaml`

**Comment by HymEric** [comment]
I have more than one video, each have 7 frames, and I follow your structure. Does the defference of name matter?

This is:
 VIDEO_BEA:
    train: ["VIDEO_BEA/train_HR/"]
    train_pair: ['VIDEO_BEA/train_LRx4/']
    val: ["VIDEO_BEA/valid_HR/"]
    val_pair: ["VIDEO_BEA/valid_LRx4/"]
    param:
      parser: custom_pairs

**Comment by HymEric** [comment]
And if I don't use pair-data it is fine to train.

**Comment by LoSealL** [comment]
debugging, be patient plz...

**Comment by HymEric** [comment]
hi, I have solved it just by set rewind=True about lr-image setting.
In `custome_pairs` line 20: `self.files = [ImageFile(fp).attach_pair(p,rewind=True) for fp, p in zip(urls, pair)]`

**Comment by LoSealL** [comment]
@HymEric This is not correct, for `rewind=True` just force the file object to reopen when it reaches EOF, while in the training we need to randomly seek file position. 
I only seek `self.files` but forget to seek `self.files.pair`, so it raise EOF during training. Check my latest `dev` branch (almost the same as `master`) 'cause I've fixed it yesterday.

**Comment by HymEric** [comment]
Yes, you are right. But you means it also just by adding line `vf.pair.seek(i)` to correct it? 
And I do it and really work. Thank you.

**Comment by LoSealL** [comment]
Yes, to ensure the file and its corresponded pair file seek to the same position (i.e. the same frame id)

**Comment by HymEric** [comment]
> Yes, to ensure the file and its corresponded pair file seek to the same position (i.e. the same frame id)

And I see the GPU utilization is low about 1-2G, what can I di if I want to train more faster with all GPU resources or 16G?

**Comment by LoSealL** [comment]
@HymEric Are you using `--cuda` flag? And you could also increase batch size and patch size, by adding the following section into `Parameters/vespcn.yml` :

```yaml
batch: 64
patch_size: 96
```

**Comment by HymEric** [comment]
Thank you. But I mean in tensorflow, there is no cuda flag.

**Comment by LoSealL** [comment]
It's the same. The parameter file of tensorflow is in 'Train/parameters/vespcn.yaml`. Increasing batch and patch_size should help.

**Comment by HymEric** [comment]
ok. Besides, in README.md to add a new model just need to add `model.py` and modify `__init__.y` in VSR.Model. How about the other parameters such as `yaml` file hyper-parameters about model?

**Comment by LoSealL** [comment]
It's a little complicated to explain, but easy to use:
1. The `run.py` automatically searches `*.yaml` file in `parameters` directory, with the same name as the model.
2. In `*.yaml` file, you just need to add a section like:
    ```yaml
    model-name:
       param1: foo
       param2: bar
    ```
   The parameter name will send to model's `__init__`'s `kwargs` argument. The mandatory parameters are `channel` and `scale`.
It's easy to copy a yaml file and modify any section related to your own model.
3. I also offer a `-p` option to explicitly assign a config file.

**Comment by HymEric** [comment]
Thank you.
