### ISSUE TITLE
Problem with "Train your first model" code

### ISSUE THREAD

**Issue by dtlloyd** [LoSealL/VideoSuperResolution#36]
Hi,

I successfully installed VSR. However when I try to run

```
python run.py --model=srcnn --dataset=91-image --test=set14
```

I encounter an error. The traceback reads:

> WARNING:tensorflow:From /home/david/miniconda/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From /home/david/SAT-FIRE/Codes/Data Fusion/SCRNN with Tensorflow Example/VideoSuperResolution-master/VSR/Framework/SuperResolution.py:118: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
WARNING:tensorflow:From /home/david/SAT-FIRE/Codes/Data Fusion/SCRNN with Tensorflow Example/VideoSuperResolution-master/VSR/Util/Utility.py:139: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
2019-04-25 11:22:29.679578: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-04-25 11:22:29.700841: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3100230000 Hz
2019-04-25 11:22:29.701348: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x55cebbc55a80 executing computations on platform Host. Devices:
2019-04-25 11:22:29.701364: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
INFO:tensorflow:Fitting: SRCNN
frames is empty. [size=12800]
| 2019-04-25 11:22:29 | Epoch: 1/50 | LR: 0.01 |
0batch [00:00, ?batch/s]
frames is empty. [size=10]
Test: 0it [00:00, ?it/s]

Traceback (most recent call last):
  File "/home/david/miniconda/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/home/david/miniconda/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/david/miniconda/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'input/lr' with dtype uint8 and shape [?,?,?,?]
	 [[{{node input/lr}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 46, in <module>
    tf.app.run(main)
  File "/home/david/miniconda/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "run.py", line 42, in main
    return Run.run(*args[0][1:], **additional_functions)
  File "/home/david/SAT-FIRE/Codes/Data Fusion/SCRNN with Tensorflow Example/VideoSuperResolution-master/VSR/Tools/Run.py", line 319, in run
    t.fit([train_loader, val_loader], train_config)
  File "/home/david/SAT-FIRE/Codes/Data Fusion/SCRNN with Tensorflow Example/VideoSuperResolution-master/VSR/Framework/Trainer.py", line 356, in fit
    self.fn_train_each_epoch()
  File "/home/david/SAT-FIRE/Codes/Data Fusion/SCRNN with Tensorflow Example/VideoSuperResolution-master/VSR/Framework/Trainer.py", line 272, in fn_train_each_epoch
    v.summary_writer.add_summary(self.model.summary(), v.global_step)
  File "/home/david/SAT-FIRE/Codes/Data Fusion/SCRNN with Tensorflow Example/VideoSuperResolution-master/VSR/Framework/SuperResolution.py", line 216, in summary
    feed_dict=self.feed_dict)
  File "/home/david/miniconda/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/david/miniconda/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/david/miniconda/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/home/david/miniconda/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'input/lr' with dtype uint8 and shape [?,?,?,?]
	 [[node input/lr (defined at /home/david/SAT-FIRE/Codes/Data Fusion/SCRNN with Tensorflow Example/VideoSuperResolution-master/VSR/Framework/SuperResolution.py:117) ]]

Caused by op 'input/lr', defined at:
  File "run.py", line 46, in <module>
    tf.app.run(main)
  File "/home/david/miniconda/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "run.py", line 42, in main
    return Run.run(*args[0][1:], **additional_functions)
  File "/home/david/SAT-FIRE/Codes/Data Fusion/SCRNN with Tensorflow Example/VideoSuperResolution-master/VSR/Tools/Run.py", line 305, in run
    with trainer(model, root, verbosity) as t:
  File "/home/david/SAT-FIRE/Codes/Data Fusion/SCRNN with Tensorflow Example/VideoSuperResolution-master/VSR/Framework/Trainer.py", line 109, in __enter__
    self._startup()
  File "/home/david/SAT-FIRE/Codes/Data Fusion/SCRNN with Tensorflow Example/VideoSuperResolution-master/VSR/Framework/Trainer.py", line 103, in _startup
    self.model.compile()
  File "/home/david/SAT-FIRE/Codes/Data Fusion/SCRNN with Tensorflow Example/VideoSuperResolution-master/VSR/Framework/SuperResolution.py", line 84, in compile
    self.build_graph()
  File "/home/david/SAT-FIRE/Codes/Data Fusion/SCRNN with Tensorflow Example/VideoSuperResolution-master/VSR/Models/Srcnn.py", line 43, in build_graph
    super(SRCNN, self).build_graph()
  File "/home/david/SAT-FIRE/Codes/Data Fusion/SCRNN with Tensorflow Example/VideoSuperResolution-master/VSR/Framework/SuperResolution.py", line 117, in build_graph
    name='input/lr'))
  File "/home/david/miniconda/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py", line 2077, in placeholder
    return gen_array_ops.placeholder(dtype=dtype, shape=shape, name=name)
  File "/home/david/miniconda/lib/python3.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 5791, in placeholder
    "Placeholder", dtype=dtype, shape=shape, name=name)
  File "/home/david/miniconda/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/home/david/miniconda/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/david/miniconda/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/home/david/miniconda/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'input/lr' with dtype uint8 and shape [?,?,?,?]
	 [[node input/lr (defined at /home/david/SAT-FIRE/Codes/Data Fusion/SCRNN with Tensorflow Example/VideoSuperResolution-master/VSR/Framework/SuperResolution.py:117) ]]

Any ideas what is causing this problem?

**Comment by rzumer** [comment]
Usually it is that the dataset is not found at the expected location, so no image/frame can be loaded.

**Comment by LoSealL** [comment]
Yes, please download datasets before starting training:
```bash
python prepare_data.py --filter=91-image
```

**Comment by dtlloyd** [comment]
Thanks for your replies. You are both correct.

For the complete novices, like me, who are also having this problem, I solved the problem by.

1. Changing the root directory in settings.yaml to the folder location where the images (91-image and set14 in the case above) live.
2. Making sure SRCNN.tar.gz file was downloaded and extracted in the Results folder. If you run prepare_data.py as per the readme, SRCNN.tar.gz may not download, even if you answer yes when asked about it.

Things seem to be running fine for me now.

**Comment by RuyiLuo** [comment]
> Thanks for your replies. You are both correct.
> 
> For the complete novices, like me, who are also having this problem, I solved the problem by.
> 
> 1. Changing the root directory in datasets.yaml to the folder location where the images (91-image and set14 in the case above) live.
> 2. Making sure SRCNN.tar.gz file was downloaded and extracted in the Results folder. If you run prepare_data.py as per the readme, SRCNN.tar.gz may not download, even if you answer yes when asked about it.
> 
> Things seem to be running fine for me now.

How do you download the SRCNN.tar.gz?
First, I ran the prepare_data.py as the readyme, but I can't download it.
Than, I directly copy the url of SRCNN to my chrome, it show Not Found in the web. 
How can I get it?

**Comment by RuyiLuo** [comment]
I successfully install VSR, but we I try to run

`python run.py --model=srcnn --dataset=91-image --test=set14
`
I have also encounter a problem, as follow

> WARNING:tensorflow:From /home/ryluo/Downloads/yes/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From /home/ryluo/Desktop/VideoSuperResolution-master/VSR/Framework/SuperResolution.py:118: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
WARNING:tensorflow:From /home/ryluo/Desktop/VideoSuperResolution-master/VSR/Util/Utility.py:139: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
2019-05-01 15:48:33.567254: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-05-01 15:48:33.570479: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2303990000 Hz
2019-05-01 15:48:33.570677: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x2ad5bb0 executing computations on platform Host. Devices:
2019-05-01 15:48:33.570694: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
Traceback (most recent call last):
  File "/home/ryluo/Desktop/VideoSuperResolution-master/VSR/DataLoader/Loader.py", line 129, in __init__
    _m = importlib.import_module(parser)
  File "/home/ryluo/Downloads/yes/envs/tensorflow/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 948, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'default_parser'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 46, in <module>
    tf.app.run(main)
  File "/home/ryluo/Downloads/yes/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "run.py", line 42, in main
    return Run.run(*args[0][1:], **additional_functions)
  File "/home/ryluo/Desktop/VideoSuperResolution-master/VSR/Tools/Run.py", line 311, in run
    augmentation=True)
  File "/home/ryluo/Desktop/VideoSuperResolution-master/VSR/DataLoader/Loader.py", line 325, in __init__
    augmentation, **kwargs)
  File "/home/ryluo/Desktop/VideoSuperResolution-master/VSR/DataLoader/Loader.py", line 131, in __init__
    _m = importlib.import_module(f'.{parser}', 'VSR.DataLoader.Parser')
  File "/home/ryluo/Downloads/yes/envs/tensorflow/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 973, in _gcd_import
  File "<frozen importlib._bootstrap>", line 923, in _sanity_check
SystemError: Parent module 'VSR.DataLoader.Parser' not loaded, cannot perform relative import

Any ideas what is causing this problem?

**Comment by dtlloyd** [comment]
SRCNN.tar.gz can be found here:
https://github.com/LoSealL/Model/releases/download/srcnn/srcnn.tar.gz

**Comment by RuyiLuo** [comment]
> SRCNN.tar.gz can be found here:
> https://github.com/LoSealL/Model/releases/download/srcnn/srcnn.tar.gz

Thanks for your replies,  I can get it from this url.

Did you run thought all codes in VSR package?
However, I encounter another problem when I use VSR package.
can you leave your some contact details? For example, Wechat or Email? 

Look forward to your reply

**Comment by LoSealL** [comment]
Couldn't reply in time these days, after the vacation, I will keep in touch in this thread with you. @RuyiLuo

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: RuyiLuo <notifications@github.com>
发送时间: Wednesday, May 1, 2019 5:26:32 PM
收件人: LoSealL/VideoSuperResolution
抄送: Tang, Wenyi; Comment
主题: Re: [LoSealL/VideoSuperResolution] Problem with "Train your first model" code (#36)


SRCNN.tar.gz can be found here:
https://github.com/LoSealL/Model/releases/download/srcnn/srcnn.tar.gz<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FLoSealL%2FModel%2Freleases%2Fdownload%2Fsrcnn%2Fsrcnn.tar.gz&data=02%7C01%7C%7Ca5ff821d43a84b32180c08d6ce171a7a%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636922995955440894&sdata=T4sG%2FbZKgTqE7ot9kDofJOfib9Dvejh%2BQn%2BZeWJ6hHQ%3D&reserved=0>

Thanks for your replies, I can get it from this url.

Did you run thought all codes in VSR package?
However, I encounter another problem when I use VSR package.
can you leave your some contact details? For example, Wechat or Email?

Look forward to your reply

―

**Comment by wsqat** [comment]
Hello, can you tell me how to resolve this erroe ?

@LoSealL @RuyiLuo 
$ python run.py --model=srcnn --test=set5              

ModuleNotFoundError: No module named 'default_parser'
……
SystemError: Parent module 'VSR.DataLoader.Parser' not loaded, cannot perform relative import

**Comment by LoSealL** [comment]
@RuyiLuo Do you still have problems? What're they exactly?
@wsqat Check the code integrity: any file missing under `VSR/DataLoader/Parser`?

**Comment by LoSealL** [comment]
See new added [wiki](https://github.com/LoSealL/VideoSuperResolution/wiki/SRCNN)

**Comment by wsqat** [comment]
That's ok!
