### ISSUE TITLE
vespcn  run error

### ISSUE THREAD

**Issue by wsqat** [LoSealL/VideoSuperResolution#51]
$ python run.py --model vespcn --test=set5
Traceback (most recent call last):
  File "run.py", line 46, in <module>
    tf.app.run(main)
  File "/mnt/lustre/wangshiqing/venv_3.6/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "run.py", line 42, in main
    return Run.run(*args[0][1:], **additional_functions)
  File "/mnt/lustre/wangshiqing/SR/VideoSuperResolution/VSR/Tools/Run.py", line 308, in run
    with trainer(model, root, verbosity) as t:
  File "/mnt/lustre/wangshiqing/SR/VideoSuperResolution/VSR/Framework/Trainer.py", line 109, in __enter__
    self._startup()
  File "/mnt/lustre/wangshiqing/SR/VideoSuperResolution/VSR/Framework/Trainer.py", line 103, in _startup
    self.model.compile()
  File "/mnt/lustre/wangshiqing/SR/VideoSuperResolution/VSR/Framework/SuperResolution.py", line 84, in compile
    self.build_graph()
  File "/mnt/lustre/wangshiqing/SR/VideoSuperResolution/VSR/Models/Vespcn.py", line 110, in build_graph
    w, f = self._me(input_center, frames[i])
  File "/mnt/lustre/wangshiqing/SR/VideoSuperResolution/VSR/Models/Vespcn.py", line 58, in _me
    flow0 = self._flow_coarse(x0, x1)
  File "/mnt/lustre/wangshiqing/SR/VideoSuperResolution/VSR/Models/Vespcn.py", line 37, in _flow_coarse
    x = self.relu_conv2d(x, 24, 5, strides=2)
  File "/mnt/lustre/wangshiqing/SR/VideoSuperResolution/VSR/Framework/LayersHelper.py", line 69, in conv2d
    nn.build(x.shape.as_list())
  File "/mnt/lustre/wangshiqing/venv_3.6/lib/python3.6/site-packages/tensorflow/python/layers/convolutional.py", line 133, in build
    raise ValueError('The channel dimension of the inputs '
ValueError: The channel dimension of the inputs should be defined. Found `None`.

**Comment by LoSealL** [comment]
You are wrong with arguments. Please use like below:
```bash
# For Train
python run.py --model vespcn --dataset GOPRO --epochs 100 --memory_limit 2GB
# For Test
# (optional) get weights
cd ..
python prepare_data.py --filter vespcn
cd Train
python run.py --model vespcn --test vid4
```

**Comment by wsqat** [comment]
File "/mnt/lustre/wangshiqing/SR/VideoSuperResolution/VSR/Framework/LayersHelper.py", line 71, in conv2d

```
    print(x.shape)
    nn.build(x.shape.as_list())
```
(?, ?, ?, ?)

**Comment by LoSealL** [comment]
I think your data is not correct.

**Comment by wsqat** [comment]
1、`python run.py --model vespcn --data_config ../UTest/data/fake_datasets.yml --dataset videopair -v`
2、../UTest/data/fake_datasets.yml 
  VIDEOPAIR:
    train: "video/custom_pair/hr"
    train_pair: "video/custom_pair/lr"
    val: "video/custom_pair/hr"
    val_pair: "video/custom_pair/lr"
    test: "video/custom_pair/hr"
    test_pair: "video/custom_pair/lr"
    param:
      parser: custom_pairs


3、`vi /mnt/lustre/wangshiqing/SR/VideoSuperResolution/VSR/Tools/Run.py`
104 def fetch_datasets(data_config_file, opt):
105   all_datasets = load_datasets(data_config_file)
106   print(all_datasets)

4、 log as follows
'VIDEOPAIR': {'name': 'VIDEOPAIR', 'mode': 'pil-image1', 'train': [PosixPath('/mnt/lustre/wangshiqing/SR/VideoSuperResolution/datasets/video/custom_pair/hr/001.png'), PosixPath('/mnt/lustre/wangshiqing/SR/VideoSuperResolution/datasets/video/custom_pair/hr/002.png'), PosixPath('/mnt/lustre/wangshiqing/SR/VideoSuperResolution/datasets/video/custom_pair/hr/003.png'),
 PosixPath('/mnt/lustre/wangshiqing/SR/VideoSuperResolution/datasets/video/custom_pair/lr/093.png'), PosixPath('/mnt/lustre/wangshiqing/SR/VideoSuperResolution/datasets/video/custom_pair/lr/094.png'), PosixPath('/mnt/lustre/wangshiqing/SR/VideoSuperResolution/datasets/video/custom_pair/lr/095.png'), PosixPath('/mnt/lustre/wangshiqing/SR/VideoSuperResolution/datasets/video/custom_pair/lr/096.png'), PosixPath('/mnt/lustre/wangshiqing/SR/VideoSuperResolution/datasets/video/custom_pair/lr/097.png'), PosixPath('/mnt/lustre/wangshiqing/SR/VideoSuperResolution/datasets/video/custom_pair/lr/098.png'), PosixPath('/mnt/lustre/wangshiqing/SR/VideoSuperResolution/datasets/video/custom_pair/lr/099.png'), PosixPath('/mnt/lustre/wangshiqing/SR/VideoSuperResolution/datasets/video/custom_pair/lr/100.png')], 'parser': 'custom_pairs'}, 'GHOST': {'name': 'GHOST', 'mode': 'pil-image1', 'train': []}, 'BAR': {'name': 'BAR', 'mode': 'pil-image1', 'test': []}}



=============================
| [model]: vespcn
| [output_color]: RGB
| [train_data_crop]: random
| [val_data_crop]: random
| [epochs]: 50
| [steps_per_epoch]: 200
| [val_num]: 10
| [threads]: 1
| [seed]: None
| [output_index]: -1
| [c]: None
| [p]: None
| [test]: None
| [infer]: None
| [save_dir]: ../Results
| [data_config]: ../UTest/data/fake_datasets.yml
| [dataset]: videopair
| [memory_limit]: None
| [comment]: None
| [add_custom_callbacks]: None
| [f]: None
| [f2]: None
| [f3]: None
| [export]: False
| [freeze]: False
| [auto_rename]: True
| [random_val]: True
| [ensemble]: False
| [v]: True
| [h]: False
| [help]: False
| [helpfull]: False
| [helpshort]: False
| [batch]: 4
| [patch_size]: 96
| [depth]: 3
| [lr]: 0.0001
| [lr_decay]: {'method': 'multistep', 'decay_step': [], 'decay_rate': 1}
| [vespcn]: {'depth': 3, 'beta': 1, 'gamma': 0.01, 'scale': 4, 'channel': 3, 'weight_decay': 0}
| [beta]: 1
| [gamma]: 0.01
| [scale]: 4
| [channel]: 3
| [weight_decay]: 0
| [root]: ../Results/vespcn
=============================

(?, ?, ?, ?)
(?, ?, ?, ?)
Traceback (most recent call last):
  File "run.py", line 46, in <module>
    tf.app.run(main)
  File "/mnt/lustre/wangshiqing/venv_3.6/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "run.py", line 42, in main
    return Run.run(*args[0][1:], **additional_functions)
  File "/mnt/lustre/wangshiqing/SR/VideoSuperResolution/VSR/Tools/Run.py", line 309, in run
    with trainer(model, root, verbosity) as t:
  File "/mnt/lustre/wangshiqing/SR/VideoSuperResolution/VSR/Framework/Trainer.py", line 109, in __enter__
    self._startup()
  File "/mnt/lustre/wangshiqing/SR/VideoSuperResolution/VSR/Framework/Trainer.py", line 103, in _startup
    self.model.compile()
  File "/mnt/lustre/wangshiqing/SR/VideoSuperResolution/VSR/Framework/SuperResolution.py", line 84, in compile
    self.build_graph()
  File "/mnt/lustre/wangshiqing/SR/VideoSuperResolution/VSR/Models/Vespcn.py", line 111, in build_graph
    w, f = self._me(input_center, frames[i])
  File "/mnt/lustre/wangshiqing/SR/VideoSuperResolution/VSR/Models/Vespcn.py", line 59, in _me
    flow0 = self._flow_coarse(x0, x1)
  File "/mnt/lustre/wangshiqing/SR/VideoSuperResolution/VSR/Models/Vespcn.py", line 38, in _flow_coarse
    x = self.relu_conv2d(x, 24, 5, strides=2)
  File "/mnt/lustre/wangshiqing/SR/VideoSuperResolution/VSR/Framework/LayersHelper.py", line 71, in conv2d
    nn.build(x.shape.as_list())
  File "/mnt/lustre/wangshiqing/venv_3.6/lib/python3.6/site-packages/tensorflow/python/layers/convolutional.py", line 133, in build
    raise ValueError('The channel dimension of the inputs '
ValueError: The channel dimension of the inputs should be defined. Found `None`.

**Comment by LoSealL** [comment]
lastest `master` or `dev` branch?
And your tensorflow's version? Are you using TF2.0?

**Comment by wsqat** [comment]
TF  1.8.0


 
---Original---

**Comment by LoSealL** [comment]
Can you update to `1.12.0`? There're many ops related to TF>=1.12.0

**Comment by wsqat** [comment]
I  will try it ,  tks


 
---Original---

**Comment by LoSealL** [comment]
I confirm it's based on `tf.pad`, which was addressed after version `1.9.0`.

**Comment by wsqat** [comment]
After update TF 1.12.0 , that's ok!   Tks，

**Comment by wsqat** [comment]
I want to train vsr use video SR by vespcn, but error as follows.
Could you tell me how to deploy the video dataset?
@LoSealL 

` python run.py --model vespcn --data_config ../UTest/data/fake_datasets.yml --dataset videopair -v --epochs 1100`

`vi ../UTest/data/fake_datasets.yml`
```
  VIDEOPAIR:
    train: [video/custom_pair/hr]
    train_pair: [video/custom_pair/lr]
    val: [video/custom_pair/hr]
    val_pair: [video/custom_pair/lr]
    test: [video/custom_pair/hr]
    test_pair: [video/custom_pair/lr]
    param:
      parser: custom_pairs

```



```

| [root]: ../Results/vespcn
=============================

2019-05-18 15:40:31.726477: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
INFO:tensorflow:Restoring parameters from ../Results/vespcn/save/vespcn-sc4-ep1000.ckpt
INFO:tensorflow:Fitting: VESPCN
  0%|          | 0/200 [00:00<?, ?batch/s]| 2019-05-18 15:47:03 | Epoch: 1001/1100 | LR: 0.0001 |

Traceback (most recent call last):
  File "run.py", line 46, in <module>
    tf.app.run(main)
  File "/mnt/lustre/wangshiqing/venv_3.6/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "run.py", line 42, in main
    return Run.run(*args[0][1:], **additional_functions)
  File "/mnt/lustre/wangshiqing/SR/VideoSuperResolution/VSR/Tools/Run.py", line 323, in run
    t.fit([train_loader, val_loader], train_config)
  File "/mnt/lustre/wangshiqing/SR/VideoSuperResolution/VSR/Framework/Trainer.py", line 356, in fit
    self.fn_train_each_epoch()
  File "/mnt/lustre/wangshiqing/SR/VideoSuperResolution/VSR/Framework/Trainer.py", line 261, in fn_train_each_epoch
    self.fn_train_each_step(label, feature, name, post)
  File "/mnt/lustre/wangshiqing/SR/VideoSuperResolution/VSR/Framework/Trainer.py", line 282, in fn_train_each_step
    epochs=v.epoch)
  File "/mnt/lustre/wangshiqing/SR/VideoSuperResolution/VSR/Framework/SuperResolution.py", line 173, in train_batch
    list(self.train_metric.values()) + loss, feed_dict=self.feed_dict)
  File "/mnt/lustre/wangshiqing/venv_3.6/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/mnt/lustre/wangshiqing/venv_3.6/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1128, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (4, 24, 24, 3) for Tensor 'input/lr:0', which has shape '(?, 3, ?, ?, 3)'



```

**Comment by LoSealL** [comment]
1. Please use `Data/datasets.yaml` as data config file (as default)
2. If you intend to use personal dataset, add an entry in config file like below:
  ```yaml
   # name must be UPPER-CASE
   ENTRYNAME:
     train: ["path/to/training/hr"]
     val: ["path/to/validation/hr"]
     test: ["path/to/testing/hr"]
     param:
       parser: default_parser
   ```
In `path/to/xxx/hr`:
> |hr
>---|video001
>------|Frame001.png
>------|Frame002.png
>---|video002
>...

Moreover, if you have customized LR, change `default_parser` to `custom_pairs` and add `xxx_pair`:
   ```yaml
   ENTRYNAME:
     train: ["path/to/training/hr"]
     train_pair: ["path/to/training/lr"]
     val: ["path/to/validation/hr"]
     val_pair: ["path/to/validation/lr"]
     test: ["path/to/testing/hr"]
     test_pair: ["path/to/testing/lr"]
     param:
       parser: custom_pairs
   ```

The only thing to take care about is: the file order in HR and LR must be the same.
> |hr
>---|video001
>------|Frame001_HR.png
>------|Frame002_HR.png
>---|video002
>...
> |lr
>---|video001
>------|Frame001_LR.png
>------|Frame002_LR.png
>---|video002
>...

**Comment by wsqat** [comment]
OK，tks！


 
---Original---

**Comment by wsqat** [comment]
@LoSealL 
Hello, I want to know how to define the model, which I want to infer the test sets?
`
python run.py --model srcnn --epochs=1000 --test vid4
`
Is this OK?

Hope you replay as soon as possible!

**Comment by LoSealL** [comment]
For the definition of a new model, there is only a simple introduction: https://github.com/LoSealL/VideoSuperResolution/blob/master/Docs/Adding%20new%20model.md
But you can refer to existing codes, I think it may be a good start to modify some well-known models.

If you just want to test on another data, use `--infer` or `-t`:
```
python run.py --model srcnn --infer /somewhere/img/*.png
# or (pytorch)
python eval.py srcnn --cuda -t /somewhere/img/*.png
```

Your script has a little mistake, you should write like this:
`python run.py --model srcnn --epochs 1000 --dataset div2k --test vid4`
Because:
1. `run.py` combines training and testing, `--epochs 1000` means you want to train 1000 epochs.
