### ISSUE TITLE
Issue with DUF model.

### ISSUE THREAD

**Issue by RuyiLuo** [LoSealL/VideoSuperResolution#56]
When I run as follows:
```
python run.py --model=srcnn --dataset=MYDATA
python run.py --model=rcan --dataset=MYDATA
python run.py --model=cdn --dataset=MYDATA
```
There are no any problems.
But, When I run,
`python run.py --model=duf --dataset=MYDATA`

Traceback:
```
| 2019-06-01 17:14:55 | Epoch: 1/50 | LR: 0.0001 |
  0%|                                                                                                                                                     | 0/200 [00:00<?, ?batch/s]
Traceback (most recent call last):
  File "run.py", line 46, in <module>
    tf.app.run(main)
  File "/home/ryluo/anaconda3/envs/tf12/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "run.py", line 42, in main
    return Run.run(*args[0][1:], **additional_functions)
  File "/home/ryluo/Desktop/VideoSuperResolution-master/VSR/Tools/Run.py", line 322, in run
    t.fit([train_loader, val_loader], train_config)
  File "/home/ryluo/Desktop/VideoSuperResolution-master/VSR/Framework/Trainer.py", line 356, in fit
    self.fn_train_each_epoch()
  File "/home/ryluo/Desktop/VideoSuperResolution-master/VSR/Framework/Trainer.py", line 261, in fn_train_each_epoch
    self.fn_train_each_step(label, feature, name, post)
  File "/home/ryluo/Desktop/VideoSuperResolution-master/VSR/Framework/Trainer.py", line 282, in fn_train_each_step
    epochs=v.epoch)
  File "/home/ryluo/Desktop/VideoSuperResolution-master/VSR/Framework/SuperResolution.py", line 173, in train_batch
    list(self.train_metric.values()) + loss, feed_dict=self.feed_dict)
  File "/home/ryluo/anaconda3/envs/tf12/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/ryluo/anaconda3/envs/tf12/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1128, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (16, 12, 12, 3) for Tensor 'input/lr:0', which has shape '(?, ?, ?, ?, 3)'
```

**What's problem when I run above code.**

Thanks, ruyi.

**Comment by LoSealL** [comment]
DUF is a video model, hence you need to feed video-format data to train it.

**Comment by RuyiLuo** [comment]
As you say, I feed video-format data to train DUF model.
But the terminal was killed automatically as follow
```
2019-06-02 12:53:00.177487: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-06-02 12:53:00.654478: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:964] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-06-02 12:53:00.655355: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties: 
name: GeForce GTX 1050 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.62
pciBusID: 0000:01:00.0
totalMemory: 3.95GiB freeMemory: 3.89GiB
2019-06-02 12:53:00.655396: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2019-06-02 12:53:11.173973: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-06-02 12:53:11.174024: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 
2019-06-02 12:53:11.174038: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N 
2019-06-02 12:53:11.174419: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 3623 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1050 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
INFO:tensorflow:Fitting: DUF
Killed
```
**My data-format**
```
  MYDATA-V:  
    train: hr_train
    val: hr_val/*.yuv     # You can still write absolute path patterns like this,
    test: [test_data*.yuv]  # or as array like this
    param:  # For MCL-V is raw data, these param must be specified
      mode: YV12
      parser: raw
      width: 1920
      height: 1080
```

**Comment by RuyiLuo** [comment]
```
(VSR) ryluo@Legion-Y7000:~/Desktop/VideoSuperResolution-master/VSRTorch$ python train.py frvsr --dataset MYDATA-v --cuda
2019-06-02 13:03:49,949 INFO: @LoSealL. Video related ops, nets...
2019-06-02 13:04:14,750 INFO: Total params: 2810661
2019-06-02 13:04:15,187 WARNING: trying to restore state for optimizer adam, but failed.
2019-06-02 13:04:15,188 INFO: Fitting: [FRVSR]
Killed
(VSR) ryluo@Legion-Y7000:~/Desktop/VideoSuperResolution-master/VSRTorch$ python train.py rbpn --cuda --dataset MYDATA-v
2019-06-02 13:06:47,903 INFO: LICENSE: RBPN is implemented by M. Haris, et. al. @alterzero
2019-06-02 13:06:47,903 WARNING: I use unsupervised flownet to estimate optical flow, rather than pyflow module.
2019-06-02 13:06:47,925 INFO: @LoSealL. Video related ops, nets...
2019-06-02 13:07:13,728 INFO: Total params: 14517449
2019-06-02 13:07:14,174 WARNING: trying to restore state for optimizer adam, but failed.
2019-06-02 13:07:14,174 INFO: Fitting: [RBPN]
Killed
(VSR) ryluo@Legion-Y7000:~/Desktop/VideoSuperResolution-master/VSRTorch$ python train.py sofvsr --cuda --dataset MYDATA-v
2019-06-02 13:10:22,983 INFO: LICENSE: SOF-VSR is implemented by Longguan Wang. @LongguanWang https://github.com/LongguangWang/SOF-VSR.
2019-06-02 13:10:49,892 INFO: Total params: 1639676
2019-06-02 13:10:50,344 WARNING: trying to restore state for optimizer opt, but failed.
2019-06-02 13:10:50,344 INFO: Fitting: [SOF]
Killed
(VSR) ryluo@Legion-Y7000:~/Desktop/VideoSuperResolution-master/VSRTorch$ python train.py vespcn --cuda --dataset MYDATA-v
2019-06-02 13:14:08,969 INFO: LICENSE: VESPCN is proposed at CVPR2017 by Twitter. Implemented by myself @LoSealL.
2019-06-02 13:14:09,005 INFO: @LoSealL. Video related ops, nets...
2019-06-02 13:14:33,185 INFO: Total params: 878787
2019-06-02 13:14:33,629 WARNING: trying to restore state for optimizer opt, but failed.
2019-06-02 13:14:33,629 INFO: Fitting: [VESPCN]
Killed
```
**It seems that the same peoblem has not been solved to video model.**

**Comment by LoSealL** [comment]
You need to add `--memory_limit=<numbers>` to avoid OOM killer. `<number>` can be 1GB, 100MB for instances. This is a CPU memory limitation.

**Comment by RuyiLuo** [comment]
That‘s OK 
Thanks.

**Comment by RuyiLuo** [comment]
When I ran `python run.py --model=duf --dataset=mydata --memory_limit=50MB` in my laptop for debug model, I have found the model can regularly train before it finish one epoch. But after that, it's time to test model, the terminal is dead。 

And When I run above code in LAB server,  it can pass through about 10 epochs no any issues,  then the server's terminal also is dead. And even the server is dead. 

I set the `epoch_num`, `val_num`, and `memory_limit`, but there are still have these problems.

Another problem is about data format.
I found when I  run VSR model, the data format seems like that 
```
  MCL-V:  # http://mcl.usc.edu/mcl-v-database/, small set videos
    train: MCL-V
    val: MCL-V/test/*.yuv     # You can still write absolute path patterns like this,
    test: [MCL-V/test/*.yuv]  # or as array like this
    param:  # For MCL-V is raw data, these param must be specified
      mode: YV12
      parser: raw
      width: 1920
      height: 1080
```
But, If I have the lr and hr video, how can I set the data format like follow:
```
  SIDD:
    train: "NTIRE19/Denoise/train/drsr_patches/**/*.png"
    train_pair: "NTIRE19/Denoise/train/noisy_patches/**/*.png"
    val: "NTIRE19/Denoise/train/gt_patches/**/*.png"
    val_pair: "NTIRE19/Denoise/train/noisy_patches/**/*.png"
    infer: ["NTIRE19/Denoise/validation_corrected"]
    param:
      parser: custom_pairs
```

**Comment by LoSealL** [comment]
I will check that. Before this, what's your total mem, gpu mem and your training yaml file?

For hr and lr videos, you can use
```yaml
MYDATA:
    train: "path/video/hr"
    train_pair: "path/video/lr"
    param:
      parser: custom_pairs
```
Under `hr` and `lr`, are a list of folders containing video frames (png files). If you want to use RAW format like that, no parser currently support it, so you have to make things around.

**Comment by RuyiLuo** [comment]
My total memory is 62.8GB, and gpu memory is 12GB.

For lr and hr videos, you mean that a folder contains a video frames?

**Comment by RuyiLuo** [comment]
And I also found the used mem is increasing with the epoch increasing.

**Comment by RuyiLuo** [comment]
I change the data format to video frames, and the model can train successfully in Lab server. 

But, when I use that data format, the psrn is `inf` sometimes during testing model, as follow.
```
| 2019-06-08 12:14:46 | Epoch: 25/10000 | LR: 0.0001 |
100%|####################################################| 200/200 [01:49<00:00,  1.94batch/s, loss=00.00004]
| Epoch average loss = 0.000063 |
Test: 100%|##################################################################| 10/10 [00:02<00:00,  3.31it/s]
mse: 0.000212, psnr: 42.779514, 
| 2019-06-08 12:16:42 | Epoch: 26/10000 | LR: 0.0001 |
100%|####################################################| 200/200 [01:48<00:00,  1.98batch/s, loss=00.00002]
| Epoch average loss = 0.000083 |
Test: 100%|##################################################################| 10/10 [00:02<00:00,  3.40it/s]
mse: 0.000236, psnr: inf, 
| 2019-06-08 12:18:36 | Epoch: 27/10000 | LR: 0.0001 |
100%|####################################################| 200/200 [01:52<00:00,  1.96batch/s, loss=00.00008]
| Epoch average loss = 0.000109 |
```
I have another interesting problem.
When I use raw video data and set the `val_num=10` in `VSR.Tools.Run.py ` to train DUF, that's means we use 10 videos to val? And when use video frames to do that, it means we use 10 frames to val?

**Comment by LoSealL** [comment]
@RuyiLuo This is some bug in `raw` parser. To quickly workaround:
1. Write your own parser in `VSR/DataLoader/Parser`
2. Use `Tools/Raw2Image.py` to convert YUV into png files, you can feed model by png files. Which means a folder including pngs representing a video clip.

`val_num=10` means 10 iterations run on validation loader. Each iteration gets a random cropped **batch**.
