### ISSUE TITLE
An error while testing the model Drrn

### ISSUE THREAD

**Issue by ofancy** [LoSealL/VideoSuperResolution#7]
When I testing model Drrn，happend an exception, What should I do? Thanks.

Caused by op 'drrn/label/hr', defined at:
  File "run.py", line 51, in <module>
    tf.app.run(main)
  File "/home/cheney/.local/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "run.py", line 40, in main
    return Run.run(**additional_functions)
  File "/home/cheney/Workspace/Python/VideoSuperResolution/VSR/Tools/Run.py", line 163, in run
    with trainer(model, root, verbosity) as t:
  File "/home/cheney/Workspace/Python/VideoSuperResolution/VSR/Framework/Trainer.py", line 74, in __enter__
    self._startup()
  File "/home/cheney/Workspace/Python/VideoSuperResolution/VSR/Framework/Trainer.py", line 68, in _startup
    self._m.compile()
  File "/home/cheney/Workspace/Python/VideoSuperResolution/VSR/Framework/SuperResolution.py", line 83, in compile
    self.build_graph()
  File "/home/cheney/Workspace/Python/VideoSuperResolution/VSR/Models/Drrn.py", line 48, in build_graph
    super(DRRN, self).build_graph()
  File "/home/cheney/Workspace/Python/VideoSuperResolution/VSR/Framework/SuperResolution.py", line 124, in build_graph
    name='label/hr'))
  File "/home/cheney/.local/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 1747, in placeholder
    return gen_array_ops.placeholder(dtype=dtype, shape=shape, name=name)
  File "/home/cheney/.local/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 5206, in placeholder
    "Placeholder", dtype=dtype, shape=shape, name=name)
  File "/home/cheney/.local/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/cheney/.local/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/home/cheney/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
    op_def=op_def)
  File "/home/cheney/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'drrn/label/hr' with dtype float and shape [?,?,?,3]
	 [[node drrn/label/hr (defined at /home/cheney/Workspace/Python/VideoSuperResolution/VSR/Framework/SuperResolution.py:124)  = Placeholder[dtype=DT_FLOAT, shape=[?,?,?,3], _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]
	 [[{{node drrn/strided_slice_1/_73}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_39_drrn/strided_slice_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

**Comment by LoSealL** [comment]
@ofancy Hi, what's your test command?
Try `python run.py --model=drrn --test=set5` to verify this.

**Comment by ofancy** [comment]
@LoSealL Hi, I'm using this this command, `python3.6 run.py --model=drrn --test=set5`, and it has same problem, asking for your help, thanks.
This is my environment configuration:
Tensorflow-gpu: 1.12.0
Python: 3.6.7

**Comment by LoSealL** [comment]
@ofancy Hi. How many epochs did you train DRRN?
By default, option `--epochs=50`, and `run.py` will check into `--save_dir` to get the checkpoint and its epoch number. If that number is less than `--epochs`, it will continue training model, in that case, it needs option `--dataset` to feed training placeholer.

**Comment by ofancy** [comment]
@LoSealL Hi,  After your suggestion, I set the option `--epochs` as epoch number while testing DRRN, It's no error. Thanks.

**Comment by ofancy** [comment]
@LoSealL  Another problem, when I train DRRN, it has a error at ` tf.add_n(tf.losses.get_regularization_losses())`, 
I have add a `regularizer` before it and it can continue training the model DRRN. It has any problem?

error message:
`Traceback (most recent call last):
  File "run.py", line 51, in <module>
    tf.app.run(main)
  File "/home/cheney/.local/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "run.py", line 40, in main
    return Run.run(**additional_functions)
  File "/home/cheney/Workspace/Python/VideoSuperResolution/VSR/Tools/Run.py", line 163, in run
    with trainer(model, root, verbosity) as t:
  File "/home/cheney/Workspace/Python/VideoSuperResolution/VSR/Framework/Trainer.py", line 74, in __enter__
    self._startup()
  File "/home/cheney/Workspace/Python/VideoSuperResolution/VSR/Framework/Trainer.py", line 68, in _startup
    self._m.compile()
  File "/home/cheney/Workspace/Python/VideoSuperResolution/VSR/Framework/SuperResolution.py", line 84, in compile
    self.build_loss()
  File "/home/cheney/Workspace/Python/VideoSuperResolution/VSR/Models/Drrn.py", line 60, in build_loss
    reg = tf.add_n(tf.losses.get_regularization_losses())
  File "/home/cheney/.local/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 2158, in add_n
    raise ValueError("inputs must be a list of at least one"
ValueError: inputs must be a list of at least oneTensor/IndexedSlices with the same dtype and shape
`

**Comment by LoSealL** [comment]
@ofancy Yeah, forget to mention that. It's a potential bug in my code. To address this, add following term in `drrn.yaml`:

```yml
drrn:
  ...
  weight_decay: 1.0e-6
```
