### ISSUE TITLE
Problems with the starting

### ISSUE THREAD

**Issue by Undercut** [LoSealL/VideoSuperResolution#82]
Hi, Thank you for your sharing and i was still learning your project.
However,I met a problem at the starting, i have downloaded the model and datasets, but i just can't test it successfully, and i tried on windows and ubuntu, met the same problem.

Seems like i didnt feed the data to the model, but i really downloaded the datasets, i was trapped here for several days. 

D:\VideoSuperResolution-master\Train>python run.py --model vespcn --test vid4
2019-07-13 20:53:26.928211: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
INFO:tensorflow:Fitting: VESPCN
frames is empty. [size=800]
| 2019-07-13 20:53:27 | Epoch: 1/50 | LR: 0.0001 |
0batch [00:00, ?batch/s]
frames is empty. [size=10]
Test: 0it [00:00, ?it/s]

Traceback (most recent call last):
  File "C:\Users\dd823\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1334, in _do_call
    return fn(*args)
  File "C:\Users\dd823\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "C:\Users\dd823\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'label' with dtype float and shape [?,3,?,?,3]
         [[{{node label}} = Placeholder[dtype=DT_FLOAT, shape=[?,3,?,?,3], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 46, in <module>
    tf.app.run(main)
  File "C:\Users\dd823\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "run.py", line 42, in main
    return Run.run(*args[0][1:], **additional_functions)
  File "d:\videosuperresolution-master\VSR\Tools\Run.py", line 322, in run
    t.fit([train_loader, val_loader], train_config)
  File "d:\videosuperresolution-master\VSR\Framework\Trainer.py", line 356, in fit
    self.fn_train_each_epoch()
  File "d:\videosuperresolution-master\VSR\Framework\Trainer.py", line 272, in fn_train_each_epoch
    v.summary_writer.add_summary(self.model.summary(), v.global_step)
  File "d:\videosuperresolution-master\VSR\Framework\SuperResolution.py", line 216, in summary
    feed_dict=self.feed_dict)
  File "C:\Users\dd823\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 929, in run
    run_metadata_ptr)
  File "C:\Users\dd823\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\dd823\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1328, in _do_run
    run_metadata)
  File "C:\Users\dd823\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'label' with dtype float and shape [?,3,?,?,3]
         [[node label (defined at d:\videosuperresolution-master\VSR\Models\Vespcn.py:94)  = Placeholder[dtype=DT_FLOAT, shape=[?,3,?,?,3], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op 'label', defined at:
  File "run.py", line 46, in <module>
    tf.app.run(main)
  File "C:\Users\dd823\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "run.py", line 42, in main
    return Run.run(*args[0][1:], **additional_functions)
  File "d:\videosuperresolution-master\VSR\Tools\Run.py", line 308, in run
    with trainer(model, root, verbosity) as t:
  File "d:\videosuperresolution-master\VSR\Framework\Trainer.py", line 109, in __enter__
    self._startup()
  File "d:\videosuperresolution-master\VSR\Framework\Trainer.py", line 103, in _startup
    self.model.compile()
  File "d:\videosuperresolution-master\VSR\Framework\SuperResolution.py", line 84, in compile
    self.build_graph()
  File "d:\videosuperresolution-master\VSR\Models\Vespcn.py", line 94, in build_graph
    name='label'))
  File "C:\Users\dd823\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\ops\array_ops.py", line 1747, in placeholder
    return gen_array_ops.placeholder(dtype=dtype, shape=shape, name=name)
  File "C:\Users\dd823\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 6251, in placeholder
    "Placeholder", dtype=dtype, shape=shape, name=name)
  File "C:\Users\dd823\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\dd823\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\util\deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "C:\Users\dd823\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 3274, in create_op
    op_def=op_def)
  File "C:\Users\dd823\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'label' with dtype float and shape [?,3,?,?,3]
         [[node label (defined at d:\videosuperresolution-master\VSR\Models\Vespcn.py:94)  = Placeholder[dtype=DT_FLOAT, shape=[?,3,?,?,3], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

**Comment by elia86** [comment]
Hi, I have encountered same problem . Could you please let me know how you solved it?

**Comment by LoSealL** [comment]
Your logs?

**Comment by elia86** [comment]
I'm using tensorflow 1.12.0. Here are the logs when I'm doing step 2 from getting started procedure. I mention here that for the first step I have downloaded manually the vespcn pre-trained weights (accessing the website related to vespcn data from prepare_data.py didn't work):

2019-10-18 09:53:17.163348: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-10-18 09:53:17.342031: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties: 
name: GeForce GTX 1080 major: 6 minor: 1 memoryClockRate(GHz): 1.7335
pciBusID: 0000:05:00.0
totalMemory: 7.93GiB freeMemory: 7.56GiB
2019-10-18 09:53:17.469279: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 1 with properties: 
name: GeForce GTX 1080 major: 6 minor: 1 memoryClockRate(GHz): 1.7335
pciBusID: 0000:06:00.0
totalMemory: 7.93GiB freeMemory: 7.82GiB
2019-10-18 09:53:17.583251: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 2 with properties: 
name: GeForce GTX 1080 major: 6 minor: 1 memoryClockRate(GHz): 1.7335
pciBusID: 0000:09:00.0
totalMemory: 7.93GiB freeMemory: 7.82GiB
2019-10-18 09:53:17.728476: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 3 with properties: 
name: GeForce GTX 1080 major: 6 minor: 1 memoryClockRate(GHz): 1.7335
pciBusID: 0000:0a:00.0
totalMemory: 7.93GiB freeMemory: 7.82GiB
2019-10-18 09:53:17.732876: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0, 1, 2, 3
2019-10-18 09:53:18.585986: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-10-18 09:53:18.586020: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 1 2 3 
2019-10-18 09:53:18.586026: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N Y Y Y 
2019-10-18 09:53:18.586029: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 1:   Y N Y Y 
2019-10-18 09:53:18.586033: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 2:   Y Y N Y 
2019-10-18 09:53:18.586036: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 3:   Y Y Y N 
2019-10-18 09:53:18.586193: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7293 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080, pci bus id: 0000:05:00.0, compute capability: 6.1)
2019-10-18 09:53:18.586558: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 7543 MB memory) -> physical GPU (device: 1, name: GeForce GTX 1080, pci bus id: 0000:06:00.0, compute capability: 6.1)
2019-10-18 09:53:18.586783: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:2 with 7543 MB memory) -> physical GPU (device: 2, name: GeForce GTX 1080, pci bus id: 0000:09:00.0, compute capability: 6.1)
2019-10-18 09:53:18.586981: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:3 with 7543 MB memory) -> physical GPU (device: 3, name: GeForce GTX 1080, pci bus id: 0000:0a:00.0, compute capability: 6.1)
INFO:tensorflow:Restoring parameters from ../Results/vespcn/save/vespcn-sc4-ep1000.ckpt
frames is empty. [size=-1]
Test: 0it [00:00, ?it/s]

frames is empty. [size=-1]
